use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ConfigTemplate {
    pub name: String,
    pub description: String,
    pub profession: Option<String>,
    pub job_title: Option<String>,
    pub company_size: Option<String>,
    pub years_experience: Option<String>,
    pub preferred_language: Option<String>,
    pub work_mode: Option<String>,
    pub llm_name: Option<String>,
    pub ollama_base_url: Option<String>,
    pub embedding_model: Option<String>,
}

impl ConfigTemplate {
    pub fn default_templates() -> Vec<ConfigTemplate> {
        vec![
            ConfigTemplate {
                name: "Software Developer - Startup".to_string(),
                description: "Full-stack developer at a startup company".to_string(),
                profession: Some("Software Developer".to_string()),
                job_title: Some("Senior".to_string()),
                company_size: Some("1-10".to_string()),
                years_experience: Some("3-5 years".to_string()),
                preferred_language: Some("JavaScript/TypeScript".to_string()),
                work_mode: Some("Remote".to_string()),
                llm_name: Some("llama3.2".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
            ConfigTemplate {
                name: "Software Developer - Enterprise".to_string(),
                description: "Backend developer at a large enterprise".to_string(),
                profession: Some("Software Developer".to_string()),
                job_title: Some("Senior".to_string()),
                company_size: Some("1000-5000".to_string()),
                years_experience: Some("5-10 years".to_string()),
                preferred_language: Some("Java".to_string()),
                work_mode: Some("Hybrid".to_string()),
                llm_name: Some("llama3.2".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
            ConfigTemplate {
                name: "Rust Developer".to_string(),
                description: "Systems programmer focused on Rust".to_string(),
                profession: Some("Software Developer".to_string()),
                job_title: Some("Mid".to_string()),
                company_size: Some("100-500".to_string()),
                years_experience: Some("3-5 years".to_string()),
                preferred_language: Some("Rust".to_string()),
                work_mode: Some("Remote".to_string()),
                llm_name: Some("codellama".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
            ConfigTemplate {
                name: "Data Scientist".to_string(),
                description: "Machine learning and data analysis specialist".to_string(),
                profession: Some("Data Scientist".to_string()),
                job_title: Some("Senior".to_string()),
                company_size: Some("500-1000".to_string()),
                years_experience: Some("3-5 years".to_string()),
                preferred_language: Some("Python".to_string()),
                work_mode: Some("Hybrid".to_string()),
                llm_name: Some("llama3.2".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
            ConfigTemplate {
                name: "DevOps Engineer".to_string(),
                description: "Infrastructure and deployment specialist".to_string(),
                profession: Some("DevOps Engineer".to_string()),
                job_title: Some("Senior".to_string()),
                company_size: Some("100-500".to_string()),
                years_experience: Some("5-10 years".to_string()),
                preferred_language: Some("Go".to_string()),
                work_mode: Some("Remote".to_string()),
                llm_name: Some("llama3.2".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
            ConfigTemplate {
                name: "Quick Start - Minimal".to_string(),
                description: "Minimal configuration to get started quickly".to_string(),
                profession: Some("Software Developer".to_string()),
                job_title: Some("Mid".to_string()),
                company_size: Some("10-100".to_string()),
                years_experience: Some("3-5 years".to_string()),
                preferred_language: Some("JavaScript/TypeScript".to_string()),
                work_mode: Some("Remote".to_string()),
                llm_name: Some("llama3.2".to_string()),
                ollama_base_url: Some("http://localhost:11434".to_string()),
                embedding_model: Some("nomic-embed-text".to_string()),
            },
        ]
    }
}
