name: Build and Release Universal Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos-universal:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add macOS targets
        run: rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Build x86_64 binary
        run: cargo build --release --target x86_64-apple-darwin

      - name: Build aarch64 binary
        run: cargo build --release --target aarch64-apple-darwin

      - name: Create universal binary and rename
        run: |
          lipo -create -output logswise-cli \
            target/x86_64-apple-darwin/release/logswise_cli_rs \
            target/aarch64-apple-darwin/release/logswise_cli_rs
          chmod +x logswise-cli

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: logswise-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
